# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Cryden\Desktop\PyQt5\ui_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditDialog(object):
    def setupUi(self, EditDialog):
        EditDialog.setObjectName("EditDialog")
        EditDialog.setWindowModality(QtCore.Qt.WindowModal)
        EditDialog.resize(855, 955)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            EditDialog.sizePolicy().hasHeightForWidth())
        EditDialog.setSizePolicy(sizePolicy)
        EditDialog.setMinimumSize(QtCore.QSize(855, 955))
        EditDialog.setMaximumSize(QtCore.QSize(855, 955))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(10)
        EditDialog.setFont(font)
        EditDialog.setStyleSheet("QGroupBox {\n"
                                 "    color: #849db8;\n"
                                 "    border: 1px solid #849db8;\n"
                                 "    font-family: Ebrima;\n"
                                 "    font-size: 12pt;\n"
                                 "    padding: 6px 3px 3px 3px;\n"
                                 "    margin-top: 0.5em;\n"
                                 "}\n"
                                 "QGroupBox::title {\n"
                                 "    subcontrol-origin: margin;\n"
                                 "    subcontrol-position: left top;\n"
                                 "    left: 6px;\n"
                                 "}\n"
                                 "QLabel {\n"
                                 "    font-family: Ebrima;\n"
                                 "    font-size: 10pt;\n"
                                 "}\n"
                                 "QLineEdit {\n"
                                 "    height: 1.5em;\n"
                                 "    font-family: Ebrima;\n"
                                 "    font-size: 10pt;    \n"
                                 "}\n"
                                 "QComboBox {\n"
                                 "    height: 1.5em;\n"
                                 "    font-family: Ebrima;\n"
                                 "    font-size: 10pt;\n"
                                 "}\n"
                                 "QCheckBox {\n"
                                 "    font-family: Ebrima;\n"
                                 "    font-size: 10pt;\n"
                                 "}\n"
                                 "QPushButton {\n"
                                 "    color: #849db8;\n"
                                 "    min-width: 6em;\n"
                                 "    padding: 5px;\n"
                                 "}")
        self.vLayout_addGame = QtWidgets.QVBoxLayout(EditDialog)
        self.vLayout_addGame.setObjectName("vLayout_addGame")
        self.gBox_topPath = QtWidgets.QGroupBox(EditDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gBox_topPath.sizePolicy().hasHeightForWidth())
        self.gBox_topPath.setSizePolicy(sizePolicy)
        self.gBox_topPath.setObjectName("gBox_topPath")
        self.hLayout_topPath = QtWidgets.QHBoxLayout(self.gBox_topPath)
        self.hLayout_topPath.setContentsMargins(0, 0, 0, 0)
        self.hLayout_topPath.setObjectName("hLayout_topPath")
        self.label_gamepath = QtWidgets.QLabel(self.gBox_topPath)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_gamepath.sizePolicy().hasHeightForWidth())
        self.label_gamepath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(14)
        self.label_gamepath.setFont(font)
        self.label_gamepath.setStyleSheet("font-size: 14pt;")
        self.label_gamepath.setTextInteractionFlags(
            QtCore.Qt.NoTextInteraction)
        self.label_gamepath.setObjectName("label_gamepath")
        self.hLayout_topPath.addWidget(self.label_gamepath)
        self.btn_open_game = QtWidgets.QPushButton(self.gBox_topPath)
        self.btn_open_game.setObjectName("btn_open_game")
        self.hLayout_topPath.addWidget(self.btn_open_game)
        self.btn_edit_game = QtWidgets.QPushButton(self.gBox_topPath)
        self.btn_edit_game.setObjectName("btn_edit_game")
        self.hLayout_topPath.addWidget(self.btn_edit_game)
        self.hLayout_topPath.setStretch(0, 1)
        self.vLayout_addGame.addWidget(self.gBox_topPath)
        self.gBox_info = QtWidgets.QGroupBox(EditDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gBox_info.sizePolicy().hasHeightForWidth())
        self.gBox_info.setSizePolicy(sizePolicy)
        self.gBox_info.setObjectName("gBox_info")
        self.fLayout_info = QtWidgets.QFormLayout(self.gBox_info)
        self.fLayout_info.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.fLayout_info.setFormAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.fLayout_info.setContentsMargins(3, 6, 0, 3)
        self.fLayout_info.setSpacing(3)
        self.fLayout_info.setObjectName("fLayout_info")
        self.label_title = QtWidgets.QLabel(self.gBox_info)
        self.label_title.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_title.setObjectName("label_title")
        self.fLayout_info.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.label_title)
        self.lineEdit_title = QtWidgets.QLineEdit(self.gBox_info)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.fLayout_info.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_title)
        self.label_url = QtWidgets.QLabel(self.gBox_info)
        self.label_url.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_url.setObjectName("label_url")
        self.fLayout_info.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.label_url)
        self.hLayout_info_url = QtWidgets.QHBoxLayout()
        self.hLayout_info_url.setSpacing(3)
        self.hLayout_info_url.setObjectName("hLayout_info_url")
        self.lineEdit_url = QtWidgets.QLineEdit(self.gBox_info)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.hLayout_info_url.addWidget(self.lineEdit_url)
        self.btn_url_open = QtWidgets.QPushButton(self.gBox_info)
        self.btn_url_open.setObjectName("btn_url_open")
        self.hLayout_info_url.addWidget(self.btn_url_open)
        self.btn_url_pull = QtWidgets.QPushButton(self.gBox_info)
        self.btn_url_pull.setObjectName("btn_url_pull")
        self.hLayout_info_url.addWidget(self.btn_url_pull)
        self.fLayout_info.setLayout(
            1, QtWidgets.QFormLayout.FieldRole, self.hLayout_info_url)
        self.label_image = QtWidgets.QLabel(self.gBox_info)
        self.label_image.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_image.setObjectName("label_image")
        self.fLayout_info.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.label_image)
        self.hLayout_info_image = QtWidgets.QHBoxLayout()
        self.hLayout_info_image.setSpacing(3)
        self.hLayout_info_image.setObjectName("hLayout_info_image")
        self.lineEdit_image = QtWidgets.QLineEdit(self.gBox_info)
        self.lineEdit_image.setObjectName("lineEdit_image")
        self.hLayout_info_image.addWidget(self.lineEdit_image)
        self.btn_image_search = QtWidgets.QPushButton(self.gBox_info)
        self.btn_image_search.setObjectName("btn_image_search")
        self.hLayout_info_image.addWidget(self.btn_image_search)
        self.fLayout_info.setLayout(
            2, QtWidgets.QFormLayout.FieldRole, self.hLayout_info_image)
        self.label_version = QtWidgets.QLabel(self.gBox_info)
        self.label_version.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_version.setObjectName("label_version")
        self.fLayout_info.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.label_version)
        self.lineEdit_version = QtWidgets.QLineEdit(self.gBox_info)
        self.lineEdit_version.setObjectName("lineEdit_version")
        self.fLayout_info.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_version)
        self.label_progpths = QtWidgets.QLabel(self.gBox_info)
        self.label_progpths.setObjectName("label_progpths")
        self.fLayout_info.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.label_progpths)
        self.frame_progpths = QtWidgets.QFrame(self.gBox_info)
        self.frame_progpths.setStyleSheet("QLineEdit {font-size: 8pt;}")
        self.frame_progpths.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_progpths.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_progpths.setObjectName("frame_progpths")
        self.vLayout_progpths = QtWidgets.QVBoxLayout(self.frame_progpths)
        self.vLayout_progpths.setContentsMargins(0, 0, 0, 0)
        self.vLayout_progpths.setSpacing(3)
        self.vLayout_progpths.setObjectName("vLayout_progpths")
        self.gLayout_progpths_title = QtWidgets.QGridLayout()
        self.gLayout_progpths_title.setObjectName("gLayout_progpths_title")
        self.label_progpths_num = QtWidgets.QLabel(self.frame_progpths)
        self.label_progpths_num.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_progpths_num.setFont(font)
        self.label_progpths_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progpths_num.setTextInteractionFlags(
            QtCore.Qt.NoTextInteraction)
        self.label_progpths_num.setObjectName("label_progpths_num")
        self.gLayout_progpths_title.addWidget(
            self.label_progpths_num, 0, 0, 1, 1)
        self.label_progpths_name = QtWidgets.QLabel(self.frame_progpths)
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_progpths_name.setFont(font)
        self.label_progpths_name.setCursor(
            QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_progpths_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progpths_name.setTextInteractionFlags(
            QtCore.Qt.NoTextInteraction)
        self.label_progpths_name.setObjectName("label_progpths_name")
        self.gLayout_progpths_title.addWidget(
            self.label_progpths_name, 0, 1, 1, 1)
        self.label_progpths_path = QtWidgets.QLabel(self.frame_progpths)
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_progpths_path.setFont(font)
        self.label_progpths_path.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progpths_path.setTextInteractionFlags(
            QtCore.Qt.NoTextInteraction)
        self.label_progpths_path.setObjectName("label_progpths_path")
        self.gLayout_progpths_title.addWidget(
            self.label_progpths_path, 0, 2, 1, 1)
        self.gLayout_progpths_title.setColumnStretch(1, 5)
        self.gLayout_progpths_title.setColumnStretch(2, 7)
        self.vLayout_progpths.addLayout(self.gLayout_progpths_title)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_progpths)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 300))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 705, 606))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gLayout_progpths_scrollArea = QtWidgets.QGridLayout(
            self.scrollAreaWidgetContents)
        self.gLayout_progpths_scrollArea.setContentsMargins(6, 6, 6, 6)
        self.gLayout_progpths_scrollArea.setHorizontalSpacing(3)
        self.gLayout_progpths_scrollArea.setVerticalSpacing(6)
        self.gLayout_progpths_scrollArea.setObjectName(
            "gLayout_progpths_scrollArea")
        for i in range(30):
            lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            lbl.setText(f"{i+1:02d}")
            lbl.setObjectName(f"label_progpths_{i+1:02d}")
            self.__dict__[f"label_progpths_{i+1:02d}"] = lbl
            self.gLayout_progpths_scrollArea.addWidget(lbl, i, 0, 1, 1)

            nm = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
            nm.setObjectName(f"lineEdit_progpths_name_{i+1:02d}")
            self.__dict__[f"lineEdit_progpths_name_{i+1:02d}"] = nm
            self.gLayout_progpths_scrollArea.addWidget(nm, i, 1, 1, 1)

            exe = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
            exe.setObjectName(f"lineEdit_progpths_exe_{i+1:02d}")
            self.__dict__[f"lineEdit_progpths_exe_{i+1:02d}"] = exe
            self.gLayout_progpths_scrollArea.addWidget(exe, i, 2, 1, 1)

        self.gLayout_progpths_scrollArea.setColumnStretch(1, 5)
        self.gLayout_progpths_scrollArea.setColumnStretch(2, 7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.vLayout_progpths.addWidget(self.scrollArea)
        self.hLayout_progpths_btns = QtWidgets.QHBoxLayout()
        self.hLayout_progpths_btns.setContentsMargins(0, 0, -1, -1)
        self.hLayout_progpths_btns.setObjectName("hLayout_progpths_btns")
        self.btn_progpths_remove = QtWidgets.QPushButton(self.frame_progpths)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_progpths_remove.sizePolicy().hasHeightForWidth())
        self.btn_progpths_remove.setSizePolicy(sizePolicy)
        self.btn_progpths_remove.setObjectName("btn_progpths_remove")
        self.hLayout_progpths_btns.addWidget(self.btn_progpths_remove)
        self.btn_progpths_browse = QtWidgets.QPushButton(self.frame_progpths)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_progpths_browse.sizePolicy().hasHeightForWidth())
        self.btn_progpths_browse.setSizePolicy(sizePolicy)
        self.btn_progpths_browse.setObjectName("btn_progpths_browse")
        self.hLayout_progpths_btns.addWidget(self.btn_progpths_browse)
        self.btn_progpths_add = QtWidgets.QPushButton(self.frame_progpths)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_progpths_add.sizePolicy().hasHeightForWidth())
        self.btn_progpths_add.setSizePolicy(sizePolicy)
        self.btn_progpths_add.setObjectName("btn_progpths_add")
        self.hLayout_progpths_btns.addWidget(self.btn_progpths_add)
        self.vLayout_progpths.addLayout(self.hLayout_progpths_btns)
        self.fLayout_info.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.frame_progpths)
        self.label_description = QtWidgets.QLabel(self.gBox_info)
        self.label_description.setObjectName("label_description")
        self.fLayout_info.setWidget(
            6, QtWidgets.QFormLayout.LabelRole, self.label_description)
        self.textEdit_description = QtWidgets.QPlainTextEdit(self.gBox_info)
        self.textEdit_description.setMinimumSize(QtCore.QSize(545, 111))
        self.textEdit_description.setMaximumSize(QtCore.QSize(545, 111))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(11)
        self.textEdit_description.setFont(font)
        self.textEdit_description.setPlaceholderText("")
        self.textEdit_description.setObjectName("textEdit_description")
        self.fLayout_info.setWidget(
            6, QtWidgets.QFormLayout.FieldRole, self.textEdit_description)
        self.vLayout_addGame.addWidget(self.gBox_info)
        self.gBox_categories = QtWidgets.QGroupBox(EditDialog)
        self.gBox_categories.setStyleSheet("QGroupBox QGroupBox {\n"
                                           "    font-size: 10pt;\n"
                                           "}")
        self.gBox_categories.setObjectName("gBox_categories")
        self.gLayout_categories = QtWidgets.QGridLayout(self.gBox_categories)
        self.gLayout_categories.setContentsMargins(3, 0, 3, 3)
        self.gLayout_categories.setObjectName("gLayout_categories")
        self.vLayout_addGame.addWidget(self.gBox_categories)
        self.gBox_tags = QtWidgets.QGroupBox(EditDialog)
        self.gBox_tags.setObjectName("gBox_tags")
        self.gLayout_tags = QtWidgets.QGridLayout(self.gBox_tags)
        self.gLayout_tags.setObjectName("gLayout_tags")
        self.vLayout_addGame.addWidget(self.gBox_tags)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.vLayout_addGame.addWidget(self.buttonBox)

        self.retranslateUi(EditDialog)
        self.buttonBox.accepted.connect(EditDialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(EditDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditDialog)

    def retranslateUi(self, EditDialog):
        _translate = QtCore.QCoreApplication.translate
        EditDialog.setWindowTitle(_translate("EditDialog", "Edit Game"))
        self.gBox_topPath.setTitle(_translate("EditDialog", "Top Path"))
        self.label_gamepath.setText(_translate("EditDialog", "_gamepath_"))
        self.btn_open_game.setText(_translate("EditDialog", "Open"))
        self.btn_edit_game.setText(_translate("EditDialog", "Edit"))
        self.gBox_info.setTitle(_translate("EditDialog", "Info"))
        self.label_title.setText(_translate("EditDialog", "Title:"))
        self.label_url.setText(_translate("EditDialog", "URL:"))
        self.btn_url_open.setText(_translate("EditDialog", "Open URL"))
        self.btn_url_pull.setText(_translate("EditDialog", "Pull Data"))
        self.label_image.setText(_translate("EditDialog", "Image Path:"))
        self.btn_image_search.setText(
            _translate("EditDialog", "Search for image"))
        self.label_version.setText(_translate("EditDialog", "Version:"))
        self.label_progpths.setText(
            _translate("EditDialog", "Program Path(s):"))
        self.label_progpths_num.setText(_translate("EditDialog", "#"))
        self.label_progpths_name.setText(
            _translate("EditDialog", "Viewable Name"))
        self.label_progpths_path.setText(
            _translate("EditDialog", "Executable Path"))
        self.btn_progpths_remove.setText(
            _translate("EditDialog", "Remove a row"))
        self.btn_progpths_browse.setText(
            _translate("EditDialog", "Browse for exe(s)..."))
        self.btn_progpths_add.setText(
            _translate("EditDialog", "Add another exe"))
        self.label_description.setText(
            _translate("EditDialog", "Description:"))
        self.gBox_categories.setTitle(_translate("EditDialog", "Categories"))
        self.gBox_tags.setTitle(_translate("EditDialog", "Tags"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditDialog = QtWidgets.QDialog()
    ui = Ui_EditDialog()
    ui.setupUi(EditDialog)
    EditDialog.show()
    sys.exit(app.exec_())
