# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Cryden\Desktop\PyQt5\ui_lineitem.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LineItem(object):
    def setupUi(self, LineItem):
        LineItem.setObjectName("LineItem")
        LineItem.setWindowModality(QtCore.Qt.WindowModal)
        LineItem.resize(1295, 130)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LineItem.sizePolicy().hasHeightForWidth())
        LineItem.setSizePolicy(sizePolicy)
        LineItem.setMinimumSize(QtCore.QSize(1295, 130))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(11)
        LineItem.setFont(font)
        LineItem.setStyleSheet("QGroupBox {\n"
                               "    color: #849db8;\n"
                               "    border: 1px solid #849db8;\n"
                               "    font-size: 8pt;\n"
                               "    font-family: Ebrima;\n"
                               "    text-decoration: underline;\n"
                               "    padding: 6px 3px 3px 3px;\n"
                               "    margin-top: 0.5em;\n"
                               "}\n"
                               "QGroupBox::title {\n"
                               "    subcontrol-origin: margin;\n"
                               "    subcontrol-position: left top;\n"
                               "    left: 6px;\n"
                               "}\n"
                               "QLabel {\n"
                               "    font-family: Ebrima;\n"
                               "    font-size: 11pt;\n"
                               "}")
        self.hLayout_lineitem = QtWidgets.QHBoxLayout(LineItem)
        self.hLayout_lineitem.setContentsMargins(0, 0, 0, 0)
        self.hLayout_lineitem.setSpacing(3)
        self.hLayout_lineitem.setObjectName("hLayout_lineitem")
        self.gBox_tools = QtWidgets.QGroupBox(LineItem)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gBox_tools.sizePolicy().hasHeightForWidth())
        self.gBox_tools.setSizePolicy(sizePolicy)
        self.gBox_tools.setObjectName("gBox_tools")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gBox_tools)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_tools_play = QtWidgets.QPushButton(self.gBox_tools)
        self.btn_tools_play.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_tools_play.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_tools_play.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_tools_play.setStyleSheet("QPushButton {\n"
                                          "    background-color: springGreen;\n"
                                          "    color: black;\n"
                                          "    font-size: 30px;\n"
                                          "    border: 1px solid black;\n"
                                          "    border-radius: 15px;\n"
                                          "    padding-left: 3px;\n"
                                          "    padding-bottom: 3px;\n"
                                          "}\n"
                                          "QPushButton::hover {\n"
                                          "    background-color: LimeGreen;\n"
                                          "}")
        self.btn_tools_play.setObjectName("btn_tools_play")
        self.verticalLayout.addWidget(self.btn_tools_play)
        self.btn_tools_web = QtWidgets.QPushButton(self.gBox_tools)
        self.btn_tools_web.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_tools_web.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_tools_web.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_tools_web.setStyleSheet("QPushButton {\n"
                                         "    background-color: LightSkyBlue;\n"
                                         "    color: black;\n"
                                         "    font-size: 10px;\n"
                                         "    border: 1px solid black;\n"
                                         "    border-radius: 15px;\n"
                                         "}\n"
                                         "QPushButton::hover {\n"
                                         "    background-color: SteelBlue;\n"
                                         "}")
        self.btn_tools_web.setObjectName("btn_tools_web")
        self.verticalLayout.addWidget(self.btn_tools_web)
        self.btn_tools_edit = QtWidgets.QPushButton(self.gBox_tools)
        self.btn_tools_edit.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_tools_edit.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_tools_edit.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_tools_edit.setStyleSheet("QPushButton {\n"
                                          "    background-color: tan;\n"
                                          "    color: black;\n"
                                          "    font-size: 12px;\n"
                                          "    border: 1px solid black;\n"
                                          "    border-radius: 15px;\n"
                                          "    padding-bottom: 2px;\n"
                                          "}\n"
                                          "QPushButton::hover {\n"
                                          "    background-color: sienna;\n"
                                          "}")
        self.btn_tools_edit.setObjectName("btn_tools_edit")
        self.verticalLayout.addWidget(self.btn_tools_edit)
        self.hLayout_lineitem.addWidget(self.gBox_tools)
        self.gBox_title = QtWidgets.QGroupBox(LineItem)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gBox_title.sizePolicy().hasHeightForWidth())
        self.gBox_title.setSizePolicy(sizePolicy)
        self.gBox_title.setMinimumSize(QtCore.QSize(203, 0))
        self.gBox_title.setObjectName("gBox_title")
        self.vLayout_title = QtWidgets.QVBoxLayout(self.gBox_title)
        self.vLayout_title.setContentsMargins(3, 0, 3, 0)
        self.vLayout_title.setSpacing(0)
        self.vLayout_title.setObjectName("vLayout_title")
        self.hLayout_lineitem.addWidget(self.gBox_title)
        self.gBox_version = QtWidgets.QGroupBox(LineItem)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gBox_version.sizePolicy().hasHeightForWidth())
        self.gBox_version.setSizePolicy(sizePolicy)
        self.gBox_version.setObjectName("gBox_version")
        self.vLayout_version = QtWidgets.QVBoxLayout(self.gBox_version)
        self.vLayout_version.setContentsMargins(3, 0, 3, 0)
        self.vLayout_version.setSpacing(0)
        self.vLayout_version.setObjectName("vLayout_version")
        self.label_version = QtWidgets.QLabel(self.gBox_version)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_version.sizePolicy().hasHeightForWidth())
        self.label_version.setSizePolicy(sizePolicy)
        self.label_version.setMinimumSize(QtCore.QSize(70, 0))
        self.label_version.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_version.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_version.setWordWrap(True)
        self.label_version.setTextInteractionFlags(
            QtCore.Qt.TextSelectableByMouse)
        self.label_version.setObjectName("label_version")
        self.vLayout_version.addWidget(self.label_version)
        self.hLayout_lineitem.addWidget(self.gBox_version)
        self.gBox_categories = QtWidgets.QGroupBox(LineItem)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gBox_categories.sizePolicy().hasHeightForWidth())
        self.gBox_categories.setSizePolicy(sizePolicy)
        self.gBox_categories.setObjectName("gBox_categories")
        self.vLayout_categories = QtWidgets.QVBoxLayout(self.gBox_categories)
        self.vLayout_categories.setContentsMargins(3, 0, 3, 0)
        self.vLayout_categories.setSpacing(0)
        self.vLayout_categories.setObjectName("vLayout_categories")
        self.label_category = QtWidgets.QLabel(self.gBox_categories)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_category.sizePolicy().hasHeightForWidth())
        self.label_category.setSizePolicy(sizePolicy)
        self.label_category.setMinimumSize(QtCore.QSize(150, 0))
        self.label_category.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_category.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_category.setWordWrap(True)
        self.label_category.setTextInteractionFlags(
            QtCore.Qt.TextSelectableByMouse)
        self.label_category.setObjectName("label_category")
        self.vLayout_categories.addWidget(self.label_category)
        self.hLayout_lineitem.addWidget(self.gBox_categories)
        self.gBox_tags = QtWidgets.QGroupBox(LineItem)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gBox_tags.sizePolicy().hasHeightForWidth())
        self.gBox_tags.setSizePolicy(sizePolicy)
        self.gBox_tags.setObjectName("gBox_tags")
        self.vLayout_tags = QtWidgets.QVBoxLayout(self.gBox_tags)
        self.vLayout_tags.setContentsMargins(3, 0, 3, 0)
        self.vLayout_tags.setSpacing(0)
        self.vLayout_tags.setObjectName("vLayout_tags")
        self.label_tags = QtWidgets.QLabel(self.gBox_tags)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_tags.sizePolicy().hasHeightForWidth())
        self.label_tags.setSizePolicy(sizePolicy)
        self.label_tags.setMinimumSize(QtCore.QSize(200, 0))
        self.label_tags.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_tags.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_tags.setWordWrap(True)
        self.label_tags.setTextInteractionFlags(
            QtCore.Qt.TextSelectableByMouse)
        self.label_tags.setObjectName("label_tags")
        self.vLayout_tags.addWidget(self.label_tags)
        self.hLayout_lineitem.addWidget(self.gBox_tags)
        self.gBox_description = QtWidgets.QGroupBox(LineItem)
        self.gBox_description.setObjectName("gBox_description")
        self.vLayout_description = QtWidgets.QVBoxLayout(self.gBox_description)
        self.vLayout_description.setContentsMargins(3, 0, 3, 0)
        self.vLayout_description.setSpacing(0)
        self.vLayout_description.setObjectName("vLayout_description")
        self.textEdit_description = QtWidgets.QPlainTextEdit(
            self.gBox_description)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.textEdit_description.sizePolicy().hasHeightForWidth())
        self.textEdit_description.setSizePolicy(sizePolicy)
        self.textEdit_description.setMaximumSize(QtCore.QSize(16777215, 111))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(11)
        self.textEdit_description.setFont(font)
        self.textEdit_description.setReadOnly(True)
        self.textEdit_description.setObjectName("textEdit_description")
        self.vLayout_description.addWidget(self.textEdit_description)
        self.hLayout_lineitem.addWidget(self.gBox_description)

        self.retranslateUi(LineItem)
        QtCore.QMetaObject.connectSlotsByName(LineItem)

    def retranslateUi(self, LineItem):
        _translate = QtCore.QCoreApplication.translate
        LineItem.setWindowTitle(_translate("LineItem", "LineItem"))
        self.gBox_tools.setTitle(_translate("LineItem", "Tools"))
        self.btn_tools_play.setText(_translate("LineItem", "▶"))
        self.btn_tools_web.setText(_translate("LineItem", "www"))
        self.btn_tools_edit.setText(_translate("LineItem", "edit"))
        self.gBox_title.setTitle(_translate("LineItem", "Title"))
        self.gBox_version.setTitle(_translate("LineItem", "Version"))
        self.label_version.setText(_translate("LineItem", "_version_"))
        self.gBox_categories.setTitle(_translate("LineItem", "Categories"))
        self.label_category.setText(_translate("LineItem", "_categories_"))
        self.gBox_tags.setTitle(_translate("LineItem", "Tags"))
        self.label_tags.setText(_translate("LineItem", "_tags_"))
        self.gBox_description.setTitle(_translate("LineItem", "GroupBox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LineItem = QtWidgets.QWidget()
    ui = Ui_LineItem()
    ui.setupUi(LineItem)
    LineItem.show()
    sys.exit(app.exec_())
